// <auto-generated />
namespace LocateSense.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DbMigrationConfiguration1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbMigrationConfiguration1));
        
        string IMigrationMetadata.Id
        {
            get { return "201411251015070_DbMigrationConfiguration1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
